### ISSUE TITLE
review phantom design

### ISSUE THREAD

**Issue by bwheelz36** [ACRF-Image-X-Institute/MRI_DistortionPhantom#9]
Hey Paul

I put a draft of the phantom design on [this branch](https://github.com/ACRF-Image-X-Institute/MRI_DistortionPhantom/tree/evolution_gear_design) (EvolutionGearPhantom.py)

I made the following changes

- adjusted hole size
- enlarged DSV to 160 so it is slightly larger than the true DSV
- extended phantom length to +- 180 mm - will guide rods be long enough? This is mainly just to make the phantom more flexible if we want to use it in other scanners; I wouldn't propose actually putting markers in the two end slices at this point.
- added large load regions for vaseline either side of central slice
- saved all marker positions to a text file

Let me know what you think...

**Comment by paulzyliu** [comment]
I got this building in FreeCAD all ok and it looks good

just a few points

- guide rod can be made as long as we want. We didn't test the guide rod fit with the test slice thought right?
- enlarging the DSV - given that we are already struggling to get good segmentation for some of the markers at R = 150, do you think this will make the images too hard to segment? (esp for the end slices)
- hole depth - I think we want to have all the markers pushed in to the bottom of each hole as that will be the most consistent? do we need to make it shallower based on the test slice?

**Comment by bwheelz36** [comment]
- I did check the guide rod fits the test slice
- DSV. hmmm. yes you're probably right. I'll change it back.
- I measured the marker (just with a ruler) and based on that changed the marker depth to 15 mm. Forgot to mention that change. it's probably worth re-doing this with some callipers though,

**Comment by bwheelz36** [comment]
another thing to think of is whether we offset the center of the markers from the center of the slice - essentially lower all the markers - to take into account the fact that in  most scanners it is difficult to get the markers as low as we can on the MRI-Linac

**Comment by paulzyliu** [comment]
> * I did check the guide rod fits the test slice
> * DSV. hmmm. yes you're probably right. I'll change it back.
> * I measured the marker (just with a ruler) and based on that changed the marker depth to 15 mm. Forgot to mention that change. it's probably worth re-doing this with some callipers though,

I think we're good to go to order the full phantom then?

**Comment by paulzyliu** [comment]
> another thing to think of is whether we offset the center of the markers from the center of the slice - essentially lower all the markers - to take into account the fact that in most scanners it is difficult to get the markers as low as we can on the MRI-Linac

Yeah this is a good point, we will probably have to do this for the Skyra

**Comment by bwheelz36** [comment]
- markers are 15 mm deep confirmed with calipers
- added a 10 mm margin for Vaseline.
- removed the two end slices I added - we can always get these manufactured later if we need them.
- Changed the DSV back to 150
- Will make a new issue to enable lowering the phantom

**Comment by bwheelz36** [comment]
- phantom is lowered by 30 mm compared to previous design.
- forced a [0,0] marker on the two end slices 

@paulzyliu wanna take a quick look before i contact evolution gear?
